on: workflow_dispatch
name: Upload/Download Artifacts

env:
  pname: mascazel
  path: root/files

jobs:
  upload:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ steps.replace-chars.outputs.pathmodified }}
    steps:
      - name: Create a File
        run: echo "hello-changed" > hello.txt

      - name: Replace Character in env save it o new env and pass to other step
        id: replace-chars
        run: |
          mkdir tey
          mkdir tey/.hidden
          echo "ali" >> tey/.hidden/ali.txt
          echo "pathmodified=$pathmodified" >> $GITHUB_OUTPUT
          echo "pathmodified=$pathmodified" >> $GITHUB_ENV

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-12345
          path: tey/.hidden
  
  download:
    runs-on: ubuntu-latest
    needs: upload
    env:
      pathmodified: ${{needs.upload.outputs.artifact-name}}
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: test-12345
      
      - name: Print Artifact
        run: |
          ls -R .
          cat hello.txt


