---

on:
  workflow_dispatch:
  workflow_call:
name: Triggered Action

jobs:
  called-run:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        id: echo
        run: |-
          sleep 10
          echo "10 seconds sleeped"
