---
on: workflow_dispatch
name: Triggered Action

jobs:
  first-run:
    runs-on: ubuntu-latest
    steps:
      - name: TriggerWorkflow
        uses: umutakkaya/github-actions-playground/.github/workflows/caller@main
