---
name: Trigger by PR Comment
on:
  issue_comment:
    types:
      - created

jobs:
  pr_comment_trigger:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:

      - name: Echo github obj
        run: echo ${{ toJson(github) }}

      - name: Echo Trigger
        run: |
          echo "Triggered by a PR comment. PR number is $NUMBER"
          echo "NUMBER=$NUMBER" >> $GITHUB_ENV
        env:
          NUMBER: ${{ github.event.issue.number }}

      - name: Checkout pull request
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.issue.number }}/head

      - name: List Files
        run: |
          ls -la .
          PR_HEAD_SHA=$(git rev-parse HEAD)
          echo $PR_HEAD_SHA

      - name: Print Github SHA
        env:
          sha: ${{ github.sha }}
        run: |
          echo "SHA is $sha"

