---
name: Trigger by PR Comment
on:
  issue_comment:
    types:
      - created

jobs:
  pr_comment_trigger:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo Trigger
        run: |
          echo "Triggered by a PR comment. PR number is $NUMBER"
        env:
          NUMBER: ${{ github.event.issue.number }}
