---
name: Trigger by PR Comment
on:
  issue_comment:
    types:
      - created

jobs:
  pr_comment_trigger:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo Trigger
        run: |
          echo "Triggered by a PR comment. PR number is $NUMBER"
          echo "NUMBER=$NUMBER" >> $GITHUB_ENV
        env:
          NUMBER: ${{ github.event.issue.number }}
      - name: Checkout PR branch
        run: |
          gh pr checkout $NUMBER
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: List Files
        run: |
          ls -la .

